FlaskWebProject1/FlaskWebProject1/__init__.py
"""
The flask application package.
"""
import os
from  . import db
from flask import Flask

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'FlaskWebProject1.sqlite'),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # a simple page that says hello
    db.init_app(app)

    #auth
    from . import views
    app.register_blueprint(views.bp)

    #blog
    from . import blog
    app.register_blueprint(blog.bp)
    app.add_url_rule('/', endpoint='index')

    return app

app= create_app()

import FlaskWebProject1.views

FlaskWebProject1/FlaskWebProject1/views.py
"""
Routes and views for the flask application.
"""

from datetime import datetime
from flask import render_template
#from FlaskWebProject1 import app
from FlaskWebProject1.db import get_db
from FlaskWebProject1.db import init_db
import functools
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash

bp = Blueprint('auth', __name__)

#@bp.route('/')
#@bp.route('/home')
def home():
    """Renders the home page."""
    #init_db()
    return render_template(
        'index.html',
        title='Home Page',
        year=datetime.now().year,
    )

@bp.route('/contact')
def contact():
    """Renders the contact page."""
    return render_template(
        'contact.html',
        title='Contact',
        year=datetime.now().year,
        message='Your contact page.'
    )

@bp.route('/about')
def about():
    """Renders the about page."""
    return render_template(
        'about.html',
        title='About',
        year=datetime.now().year,
        message='Your application description page.'
    )

@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif db.execute(
            'SELECT id FROM user WHERE username = ?', (username,)
        ).fetchone() is not None:
            error = 'User {} is already registered.'.format(username)

        if error is None:
            db.execute(
                'INSERT INTO user (username, password) VALUES (?, ?)',
                (username, generate_password_hash(password))
            )
            db.commit()
            return redirect(url_for('auth.login'))

        flash(error)

    return render_template('register.html')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None
        user = db.execute(
            'SELECT * FROM user WHERE username = ?', (username,)
        ).fetchone()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('index'))

        flash(error)

    return render_template('login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM user WHERE id = ?', (user_id,)
        ).fetchone()

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view


FlaskWebProject1/FlaskWebProject1/templates/about.html
{% extends "layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>This server was created by Vladislav Matveev</p>

{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/blog.html
{% extends 'layout.html' %}

{% block header %}
<h1>{% block title %}Posts{% endblock %}</h1>
  {% if g.user %}
<a class="action" href="{{ url_for('blog.create') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
  {% for post in posts %}
<article id="{{ post['id'] }}" class="post">
    <header>
        <div>
            <h1>{{ post['title'] }}</h1>
            <div class="about">by {{ post['username'] }} on {{ post['created'].strftime('%Y-%m-%d') }}</div>
        </div>
        {% if g.user['id'] == post['author_id'] %}
        <a class="action" href="{{ url_for('blog.update', id=post['id']) }}">Edit</a>
        {% endif %}
    </header>
    <p class="body">{{ post['body'] }}</p>
    <p>
        Completed:
        {% if post['complete'] %}
        <input id="box{{ post['id'] }}" type="checkbox" checked>
        {% endif %}
        {% if not post['complete'] %}
        <input id="box{{ post['id'] }}" type="checkbox">
        {% endif %}
        <script>
          function change_box() {
              var url = "/change_complete";
              var i = {{ post['id'] }};
              $.ajax({
                  type: "POST",
                  url: url,
                  data: {id:i},
              }).done(function (result) {
                  change_flag(result);
              });
          }

          function change_flag(value) {
              //var input = document.getElementById("box"+i);
              //input.checked = value;
          }
          i= {{ post['id'] }};
          var input = document.getElementById("box"+i);
          input.onclick = change_box;
        </script>
    </p>

    <p>
        <input id="but{{ post['id'] }}" type="button" value="Delete">
        <script>
          function delete_task() {
              var url = "/delete_task";
              var i = {{ post['id'] }};
              $.ajax({
                  type: "POST",
                  url: url,
                  data: {id:i},
              }).done(function (result) {
                  change_list(result,i);
              });
          }

          function change_list(value,i) {
              var art = document.getElementById(i);
              art.innerHTML = "";
          }
          i = {{ post['id'] }};
          var input = document.getElementById("but"+i);
          input.onclick = delete_task;
        </script>
    </p>

    <p id="comments{{ post['id'] }}">
        <input id="but_com{{ post['id'] }}" type="button" value="Show Comments">
        <script>
          function show_com() {
              var url = "https://jsonplaceholder.typicode.com/posts";
              i = {{ post['id'] }};
              $.ajax({
                  type: "GET",
                  url: url,
              }).done(function (result) {
                  change_com(result,i);
              });
          }

          function change_com(result,i) {
              mas = JSON.stringify(result[i % 100]);
              ob = JSON.parse(mas);
              p = document.getElementById("comments" + i);
              h5 = document.createElement('h5');
              h6 = document.createElement('h6');
              h5.textContent = ob.title;
              h6.textContent = ob.body;
              p.append(h5);
              p.append(h6);
            }
          i = {{ post['id'] }};
          var input = document.getElementById("but_com"+i);
          input.onclick = show_com;
        </script>
    </p>
</article>
    {% if not loop.last %}
<hr>
    {% endif %}
  {% endfor %}
{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/contact.html
{% extends "layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    Russia<br />
    Perm<br />
    <abbr title="Phone">P:</abbr>
    Only mail :)
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:vladislaw0159@gmail.com">vladislaw0159@gmail.com</a><br />
</address>

{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/create.html
{% extends 'layout.html' %}

{% block header %}
<h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
<form method="post">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] }}</textarea>
    <input type="submit" value="Save">
</form>
{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/index.html
{% extends "layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Flask</h1>
    <p class="lead">Flask is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://flask.pocoo.org/" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Flask gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://flask.pocoo.org/docs/">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>The Python Package Index is a repository of software for the Python programming language.</p>
        <p><a class="btn btn-default" href="https://pypi.python.org/pypi">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Microsoft Azure</h2>
        <p>You can easily publish to Microsoft Azure using Visual Studio. Find out how you can host your application using a free trial today.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Learn more &raquo;</a></p>
    </div>
</div>

{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Flask Application</title>
    <link rel="stylesheet" type="text/css" href="/static/content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/static/content/site.css" />
    <script src="/static/scripts/modernizr-2.6.2.js"></script>
    <script type="text/javascript" src="https://student.psu.ru/etis/js/jquery.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
     window.jQuery || document.write('<script src="{{url_for('static', filename = 'jquery.js') }}">\x3C/script>')
    </script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">To Do Server</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('blog.index') }}">Home</a></li>
                    <li><a href="{{ url_for('auth.about') }}">About</a></li>
                    <li><a href="{{ url_for('auth.contact') }}">Contact</a></li>
                    <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        {% block header %}{% endblock %}
        {% block content %}{% endblock %}
        <hr />
        <footer>
            <p>&copy; {{ year }} - Matveev Flask Application</p>
        </footer>
    </div>

    <script src="/static/scripts/jquery-1.10.2.js"></script>
    <script src="/static/scripts/bootstrap.js"></script>
    <script src="/static/scripts/respond.js"></script>
    {% block scripts %}{% endblock %}
    <!--<script src="/static/scripts/myajax.js"></script>-->
    
</body>
</html>

FlaskWebProject1/FlaskWebProject1/templates/login.html
{% extends 'layout.html' %}

{% block header %}
<h1>{% block title %}Log In{% endblock %}</h1>
{% endblock %}

{% block content %}
<form method="post">
    <label for="username">Username</label>
    <input name="username" id="username" required>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" required>
    <input type="submit" value="Log In">
</form>
{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/register.html
{% extends 'layout.html' %}

{% block header %}
<h1>{% block title %}Register{% endblock %}</h1>
{% endblock %}

{% block content %}
<form method="post">
    <label for="username">Username</label>
    <input name="username" id="username" required>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" required>
    <input type="submit" value="Register">
</form>
{% endblock %}

FlaskWebProject1/FlaskWebProject1/templates/update.html
{% extends 'layout.html' %}

{% block header %}
<h1>{% block title %}Edit "{{ post['title'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
<form method="post">
    <label for="title">Title</label>
    <input name="title" id="title"
           value="{{ request.form['title'] or post['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] or post['body'] }}</textarea>
    <input type="submit" value="Save">
</form>
<hr>
<form action="{{ url_for('blog.delete', id=post['id']) }}" method="post">
    <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
</form>
{% endblock %}